FROM frolvlad/alpine-python3
ENV PYTHONUNBUFFERED=1
RUN apk add jpeg-dev zlib-dev gcc python3-dev libc-dev
RUN mkdir -p /app/izone
WORKDIR /app/izone
COPY ./izone .
RUN pip install -r requirements.txt -i http://pypi.douban.com/simple --trusted-host pypi.douban.com